# Generated by Django 2.1 on 2019-01-01 07:20

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('main', '0003_auto_20190101_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='tag',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
