# Generated by Django 2.1 on 2019-01-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cafe_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
