# Generated by Django 2.1 on 2019-01-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190101_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='subphoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
