# Generated by Django 2.1 on 2019-01-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_cafe_subphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='insta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='locate',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='phone',
            field=models.TextField(null=True),
        ),
    ]
